/**
 * Remote registry loader: fetches the published `registry-index.json` from
 * GitHub Releases and converts it into the same `ModEntry` shape produced by
 * the local-disk loader. This lets the web UI act as a *live* mirror of the
 * registry without requiring a local clone of the `mods/` tree.
 *
 * The published index is generated by `scripts/build-index.mjs` and shipped
 * as a release asset on every merge to `main`.
 */
import type { ModEntry } from './index.js'
import { config } from '../config.js'

interface RemoteIndexShape {
  schema_version: number
  generated_at: string
  mod_count: number
  version_count: number
  mods: Record<string, { identifier: string; versions: Array<Record<string, unknown>> }>
}

function asString(v: unknown): string | undefined {
  return typeof v === 'string' && v.length > 0 ? v : undefined
}

function compareVersion(a: string, b: string): number {
  const split = (s: string) =>
    s.split(/[.\-+]/).map((p) => (/^\d+$/.test(p) ? Number(p) : p))
  const pa = split(a)
  const pb = split(b)
  for (let i = 0; i < Math.max(pa.length, pb.length); i++) {
    const xa = pa[i] ?? 0
    const xb = pb[i] ?? 0
    if (xa === xb) continue
    if (typeof xa === 'number' && typeof xb === 'number') return xa - xb
    return String(xa).localeCompare(String(xb))
  }
  return 0
}

/**
 * Fetch + parse the published registry index. Throws on network/parse
 * errors so the caller can decide to fall back to local disk.
 */
export async function fetchRemoteRegistry(): Promise<ModEntry[]> {
  const url = config.registryIndexUrl
  const res = await fetch(url, {
    headers: { Accept: 'application/json' },
    // GitHub Releases redirects to S3; node fetch follows by default.
    redirect: 'follow',
  })
  if (!res.ok) {
    throw new Error(`registry index fetch failed: ${res.status} ${res.statusText} (${url})`)
  }
  const json = (await res.json()) as RemoteIndexShape
  if (!json || typeof json !== 'object' || !json.mods) {
    throw new Error('registry index payload missing `mods` field')
  }

  const entries: ModEntry[] = []
  for (const [id, group] of Object.entries(json.mods)) {
    if (!group || !Array.isArray(group.versions) || group.versions.length === 0) continue
    // versions are pre-sorted newest-first by build-index.mjs; trust that.
    const latest = group.versions[0] as Record<string, unknown>
    const allVersions = group.versions
      .map((v) => asString(v.version))
      .filter((v): v is string => Boolean(v))
    const sortedVersions = Array.from(new Set(allVersions)).sort(
      (a, b) => -compareVersion(a, b)
    )
    entries.push({
      identifier: id,
      name: asString(latest.name) ?? id,
      abstract: asString(latest.abstract),
      author: asString(latest.author),
      license: asString(latest.license),
      kind: asString(latest.kind) ?? 'package',
      mod_type: asString(latest.mod_type),
      version: asString(latest.version) ?? '0',
      download: asString(latest.download),
      thumbnail: asString(latest.thumbnail),
      tags: Array.isArray(latest.tags) ? latest.tags.map((t) => String(t)) : [],
      release_status: asString(latest.release_status),
      multiplayer_scope: asString(latest.multiplayer_scope),
      verified: latest.x_verified === true,
      resources:
        typeof latest.resources === 'object' && latest.resources !== null
          ? (latest.resources as Record<string, unknown>)
          : undefined,
      raw: latest,
      versions: sortedVersions,
    })
  }
  entries.sort((a, b) => {
    if (a.verified !== b.verified) return a.verified ? -1 : 1
    return a.name.localeCompare(b.name, undefined, { sensitivity: 'base' })
  })
  return entries
}
